language: node_js
node_js:
  - "14"
services:
  - docker
before_install:
  - docker-compose up --build -d
  - docker-compose ps
script:
  - docker-compose exec app npm run test
after_script:
  - docker-compose down