version: "3"
services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: password123
            POSTGRES_USER: user123
            POSTGRES_DB: db123
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    
    app:
        build: ./api
        ports:
            - 3000:3000

    web:
        build: ./web
        ports:
            - "8080:8080"
        restart: always